name: Run Python Script with JSON Input

on:
  workflow_dispatch:
    inputs:
      jsonPayload:
        description: 'JSON Payload for the script'
        required: true
        default: '{"key": "value"}'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script with input payload
        run: |
          python script.py --input-payload '${{ github.event.inputs.jsonPayload }}'